Add githooks to check formatting

diff --git a/.github/workflows/flutter_analysis.yaml b/.github/workflows/flutter_analysis.yaml
--- a/.github/workflows/flutter_analysis.yaml
+++ b/.github/workflows/flutter_analysis.yaml
@@ -11,7 +11,8 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
+
       - name: Install Flutter
         uses: subosito/flutter-action@main
         with:
@@ -37,7 +38,8 @@ jobs:
         run: flutter pub get
 
       - name: Check formatting
-        run: dart format --set-exit-if-changed .
+        run: |
+          dart format --set-exit-if-changed . || (echo "::error::Code needs formatting. Run 'dart format .' locally and commit the changes." && exit 1)
 
       - name: Run analysis
         run: flutter analyze
